@Todo.Bff_HostAddress = http://localhost:5268

GET {{Todo.Bff_HostAddress}}/bff/todos?filter=all
Accept: application/json

###

GET {{Todo.Bff_HostAddress}}/bff/todos/6a66de1cc7786cefc600c37a
Accept: application/json

###

POST {{Todo.Bff_HostAddress}}/bff/todos
Content-Type: application/json

{
  "title": "React"
}

###

PUT {{Todo.Bff_HostAddress}}/bff/todos/6a66de1cc7786cefc600c37a
Content-Type: application/json

{
  "title": "Angular",
  "isCompleted": true
}

###

PATCH {{Todo.Bff_HostAddress}}/bff/todos/6a66de1cc7786cefc600c37a/toggle
Accept: application/json

###

DELETE {{Todo.Bff_HostAddress}}/bff/todos/6a66de1cc7786cefc600c37a
Accept: application/json

###

DELETE {{Todo.Bff_HostAddress}}/bff/todos/completed
Accept: application/json
