@Todo.Bff_HostAddress = http://localhost:5268

GET {{Todo.Bff_HostAddress}}/bff/todos?filter=all
Accept: application/json

###

GET {{Todo.Bff_HostAddress}}/bff/todos/6a604368d13c5ceb4a41caa5
Accept: application/json

###

POST {{Todo.Bff_HostAddress}}/bff/todos
Content-Type: application/json

{
  "Title": ""
}

###

PUT {{Todo.Bff_HostAddress}}/bff/todos/6a601b745d59c4e237e1528b
Content-Type: application/json

{
  "Title": "Angular",
  "isCompleted": true
}

###

PATCH {{Todo.Bff_HostAddress}}/bff/todos/6a604368d13c5ceb4a41caa5/toggle
Accept: application/json

###

DELETE {{Todo.Bff_HostAddress}}/bff/todos/6a601e395d59c4e237e1528d
Accept: application/json

###

DELETE {{Todo.Bff_HostAddress}}/bff/todos/completed
Accept: application/json
