@Todo.Api_HostAddress = http://localhost:5123


GET {{Todo.Api_HostAddress}}/api/todos?filter=all
Accept: application/json

###

GET {{Todo.Api_HostAddress}}/api/todos/6a5ec6de752ca749fda97d15
Accept: application/json

###

POST {{Todo.Api_HostAddress}}/api/todos
Content-Type: application/json

{
  "Title": "React"
}

###

PUT {{Todo.Api_HostAddress}}/api/todos/6a5ec6de752ca749fda97d15
Content-Type: application/json

{
  "Title": "Angular",
  "isCompleted": false
}

###

PATCH {{Todo.Api_HostAddress}}/api/todos/6a5ee2f4964581db71392122/toggle
Accept: application/json

###

DELETE {{Todo.Api_HostAddress}}/api/todos/6a5ede0d614f049a6dddf087
Accept: application/json

###

DELETE {{Todo.Api_HostAddress}}/api/todos/completed
Accept: application/json
